package BaseDatos.POJOS;
// Generated 2/10/2011 05:59:09 PM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;


/**
 * Externos generated by hbm2java
 */
public class Externos implements java.io.Serializable {

    private int id;
    private String nombre;
    private char estatus;
    private String procedencia;
    private String telefono;
    private String motivo;
    private String foto;
    private boolean  dentro;
    private Set<ExternosFecha> externosfecha = new HashSet<ExternosFecha>(0);
    
    public Externos() {
    }

    public Externos(String nombre, char estatus, String motivo, 
            String foto, boolean dentro) {
        
        this.nombre = nombre;
        this.estatus = estatus;
        this.motivo = motivo;
        this.foto = foto;
        this.dentro = dentro;
    }

    public Externos(String nombre, char estatus, String procedencia,
            String telefono, String motivo, String foto, boolean dentro) {
        
        this.nombre = nombre;
        this.estatus = estatus;
        this.procedencia = procedencia;
        this.telefono = telefono;
        this.motivo = motivo;
        this.foto = foto;
        this.dentro = dentro;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public char getEstatus() {
        return this.estatus;
    }

    public void setEstatus(char estatus) {
        this.estatus = estatus;
    }

    public String getProcedencia() {
        return this.procedencia;
    }

    public void setProcedencia(String procedencia) {
        this.procedencia = procedencia;
    }

    public String getTelefono() {
        return this.telefono;
    }

    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    public String getMotivo() {
        return this.motivo;
    }

    public void setMotivo(String motivo) {
        this.motivo = motivo;
    }

    public String getFoto() {
        return this.foto;
    }

    public void setFoto(String foto) {
        this.foto = foto;
    }

    public boolean isDentro() {
        return this.dentro;
    }

    public void setDentro(boolean dentro) {
        this.dentro = dentro;
    }

    public Set<ExternosFecha> getExterfecha() {
        return externosfecha;
    }

    public void setExterfecha(Set<ExternosFecha> externosfecha) {
        this.externosfecha = externosfecha;
    }
}
